name: Testing

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd # v2.0.0
        with:
          deno-version-file: .tool-versions
      - run: deno test
